# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: python_app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: echo
        # Сначала мы логинимся в docker.io
        run:  echo "he he"
      - name: echo
        run: |
          echo "he he: he he"
      - name: echo
        run:  >
          echo 'he he: 
          he he'
